### ISSUE TITLE
FastAPI does not work as expected

### ISSUE THREAD

**Issue by beniroquai** [ImSwitch/ImSwitch#158]
**Bug description**
It seems that, during the boot process, some return values for the creation of the API are not properly set. Below you can find some error code - ImSwitch still boots up, but the FastAPI doesn't work unfortunately. 

````
2021-12-10 17:15:35 DEBUG [GXPIPYManager -> WidefieldCamera] None
2021-12-10 17:15:42 DEBUG [GXPIPYManager -> WidefieldCamera] startlive
2021-12-10 17:15:42 DEBUG [ImConMainController] <imswitch.imcommon.model.pythontools.dictToROClass.<locals>.ROClass object at 0x7f2c1e94f0>
2021-12-10 17:15:43 ERROR [ExceptionHandler] Traceback (most recent call last):
  File "/home/uc2/Downloads/imswitch/imswitch/imcontrol/controller/server/ImSwitchServer.py", line 43, in run
    self.createAPI()
  File "/home/uc2/Downloads/imswitch/imswitch/imcontrol/controller/server/ImSwitchServer.py", line 161, in createAPI
    self.func = includePyro(includeAPI("/"+module+"/"+f, func))
  File "/home/uc2/Downloads/imswitch/imswitch/imcontrol/controller/server/ImSwitchServer.py", line 74, in includeAPI
    async def wrapper(*args, **kwargs):
  File "/home/uc2/miniforge3/envs/imswitch39/lib/python3.9/site-packages/fastapi/routing.py", line 660, in decorator
    self.add_api_route(
  File "/home/uc2/miniforge3/envs/imswitch39/lib/python3.9/site-packages/fastapi/routing.py", line 599, in add_api_route
    route = route_class(
  File "/home/uc2/miniforge3/envs/imswitch39/lib/python3.9/site-packages/fastapi/routing.py", line 406, in __init__
    self.response_field = create_response_field(
  File "/home/uc2/miniforge3/envs/imswitch39/lib/python3.9/site-packages/fastapi/utils.py", line 90, in create_response_field
    raise fastapi.exceptions.FastAPIError(
fastapi.exceptions.FastAPIError: Invalid args for response field! Hint: check that typing.Mapping[str, imswitch.imcommon.framework.qt.Signal] is a valid Pydantic field type. If you are using a return type annotation that is not a valid Pydantic field (e.g. Union[Response, dict, None]) you can disable generating the response model from the type annotation with the path operation decorator parameter response_model=None. Read more: https://fastapi.tiangolo.com/tutorial/response-model/
```

Unfortunately I cannot tell which API fails to be created. Perhaps we can isolate this easier?

**Comment by beniroquai** [comment]
Ok, I was able to isolate the problem a bit. 
It seems that the following functions or rather their responses cause problems:
```
/RecordingManager/snapImage
/CommunicationChannel/acquireImage
/CommunicationChannel/signals
```
Interestingly on Mac (perhaps unix-based systems in general?) it works. If I exclude these functions from the API generation the fastapi starts.
